"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations = {
  id: {
    // Header
    "header.search": "Cari kampanye, organisasi...",
    "header.campaigns": "Kampanye",
    "header.zakat": "Zakat",
    "header.faucet": "Faucet",
    "header.governance": "Tata Kelola",
    "header.dashboard": "Dasbor",
    "header.explorer": "Penjelajah",
    "header.contact": "Kontak",
    "header.start_campaign": "Mulai Kampanye",
    "header.connectWallet": "Hubungkan Dompet",
    "header.disconnect": "Putuskan",
    "header.balance": "Saldo",

    // Hero Section
    "hero.title": "Platform Donasi Transparan Berbasis Blockchain",
    "hero.subtitle":
      "Salurkan donasi Anda dengan aman dan transparan melalui teknologi blockchain. Setiap donasi tercatat dan dapat dilacak secara real-time.",
    "hero.startDonating": "Mulai Berdonasi",
    "hero.exploreCampaigns": "Jelajahi Kampanye",
    "hero.badge": "Tertelusuri Blockchain",
    "hero.statDonated": "DONASI",
    "hero.statTraceable": "TERTELUSURI",
    "hero.statDonors": "DONATUR",

    // Landing Roles Section
    "landing.roles.title": "Pilih Peran Anda",
    "landing.roles.subtitle": "Pilih peran Anda dan mulai berbuat baik",
    "landing.roles.donor.title": "Donatur",
    "landing.roles.donor.desc": "Dukung donasi, terima NFT bukti, dan partisipasi dalam tata kelola",
    "landing.roles.donor.button": "Mulai Berdonasi",
    "landing.roles.org.title": "Organisasi",
    "landing.roles.org.desc": "Buat kampanye Zakat, kumpulkan dana, dan verifikasi oleh Sharia Council",
    "landing.roles.org.button": "Mulai Organisasi",
    "landing.roles.gov.title": "Tata Kelola",
    "landing.roles.gov.desc": "Partisipasi dalam Community DAO dan Sharia Council untuk verifikasi proposal",
    "landing.roles.gov.button": "Tata Kelola",

    // Trusted Section
    "trusted.title": "Dipercaya oleh Institusi Terkemuka",
    "trusted.subtitle": "Kami bermitra dengan organisasi tersertifikasi dan menggunakan teknologi blockchain untuk memastikan 100% transparansi dan kepatuhan.",
    "trusted.sharia.title": "Sesuai Syariah",
    "trusted.sharia.desc": "Mengikuti prinsip Islam untuk kepatuhan Zakat dan Wakaf.",
    "trusted.award.title": "Pemenang Penghargaan",
    "trusted.award.desc": "Juara 2 Tantangan Inovasi Zakat oleh Baznas.",
    "trusted.blockchain.title": "Diamankan Blockchain",
    "trusted.blockchain.desc": "Setiap transaksi dicatat di blockchain untuk bukti yang kekal.",

    // Campaign Card
    "campaign.by": "oleh",
    "campaign.verified": "Terverifikasi",
    "campaign.unverified": "Belum Terverifikasi",
    "campaign.donors": "donatur",
    "campaign.daysLeft": "hari lagi",
    "campaign.familiesHelped": "keluarga terbantu",
    "campaign.donate": "Donasi Sekarang",

    // Campaigns Page
    "campaigns.explore": "Jelajahi Kampanye",
    "campaigns.search": "Cari kampanye...",
    "campaigns.categories": "Kategori",
    "campaigns.location": "Lokasi",
    "campaigns.organization": "Organisasi",
    "campaigns.noCategories": "Tidak ada kategori",
    "campaigns.noLocations": "Tidak ada lokasi",
    "campaigns.noOrganizations": "Tidak ada organisasi",
    "campaigns.error": "Terjadi kesalahan memuat kampanye",
    "campaigns.noResults": "Tidak ada kampanye ditemukan",
    "campaigns.clearSearch": "Hapus pencarian",
    "campaigns.loadMore": "Muat Lebih Banyak",
    "campaigns.retry": "Coba Lagi",
    "campaigns.sort": "Urutkan",
    "campaigns.campaignCount": "kampanye",
    "campaigns.findAndSupport": "Temukan dan dukung penyebab terverifikasi yang penting bagi Anda.",

    // Footer
    "footer.poweredBy": "Ditenagai oleh",
    "footer.awardBadge": "Juara 2 Tantangan Inovasi Zakat oleh Baznas",
    "footer.platform": "Platform",
    "footer.forUsers": "Untuk Pengguna",
    "footer.forOrganizations": "Untuk Organisasi",
    "footer.legalColumn": "Hukum",
    "footer.allRights": "Hak Cipta Dilindungi",
    "footer.exploreCampaigns": "Jelajahi Kampanye",
    "footer.daoGovernance": "Tata Kelola DAO",
    "footer.impactReports": "Laporan Dampak",
    "footer.donorDashboard": "Dasbor Donatur",
    "footer.myDonations": "Donasi Saya",
    "footer.becomePartner": "Menjadi Mitra",
    "footer.organizationDashboard": "Dasbor Organisasi",
    "footer.verificationProcess": "Proses Verifikasi",
    "footer.resourcesColumn": "Sumber Daya",
    "footer.privacyPolicy": "Kebijakan Privasi",
    "footer.termsOfService": "Syarat & Ketentuan",
    "footer.shariaCompliance": "Kepatuhan Syariah",
    "footer.auditLogs": "Log Audit",
    "footer.description": "Platform donasi tertraceable pertama di dunia untuk Zakat dan donasi. Memberdayakan pemberian yang transparan melalui teknologi blockchain.",

    // Dashboard
    "dashboard.totalDonated": "Total Donasi",
    "dashboard.campaignsSupported": "Kampanye Didukung",
    "dashboard.governancePower": "Kekuatan Tata Kelola",
    "dashboard.recentActivity": "Aktivitas Terbaru",
    "dashboard.walletBalance": "Saldo Dompet",
    "dashboard.overview": "Ikhtisar",
    "dashboard.taxReports": "Laporan Pajak",
    "dashboard.governanceDao": "Tata Kelola (DAO)",
    "dashboard.walletSettings": "Pengaturan Dompet",
    "dashboard.editProfile": "Edit Profil",
    "dashboard.myNftReceipts": "Bukti NFT Saya",
    "dashboard.donationHistory": "Riwayat Donasi",
    "dashboard.daoProposals": "Proposal DAO",
    "dashboard.recentDonations": "Donasi Terbaru",
    "dashboard.thisMonth": "Bulan Ini",
    "dashboard.totalImpact": "Total Dampak",
    "dashboard.categories": "Kategori",
    "dashboard.date": "Tanggal",
    "dashboard.campaignColumn": "Kampanye",
    "dashboard.amount": "Jumlah",
    "dashboard.type": "Tipe",
    "dashboard.transaction": "Transaksi",
    "dashboard.yourVotingPower": "Kekuatan Suara Anda",
    "dashboard.soulboundTokens": "Token soul-bound diperoleh melalui donasi",
    "dashboard.proposalsVoted": "Proposal yang Dipilih",
    "dashboard.participationRate": "Tingkat Partisipasi",
    "dashboard.activeProposals": "Proposal Aktif",
    "dashboard.endsIn": "Berakhir dalam",
    "dashboard.voteFor": "Suara Mendukung",
    "dashboard.voteAgainst": "Suara Menentang",
    "dashboard.howToEarnMore": "Cara Mendapatkan Lebih Banyak Kekuatan Suara",
    "dashboard.downloadTaxReports": "Unduh Laporan Pajak",
    "dashboard.taxDeductible": "Dapat Dikurangi Pajak",
    "dashboard.totalDeductible": "Total yang Dapat Dikurangi",
    "dashboard.taxBenefitEstimate": "Perkiraan Manfaat Pajak",
    "dashboard.taxRate": "tarif pajak",
    "dashboard.annualReports": "Laporan Tahunan",
    "dashboard.taxYear": "Tahun Pajak",
    "dashboard.inProgressYtd": "Berlangsung - YTD",
    "dashboard.complete": "Lengkap",
    "dashboard.downloadPdf": "Unduh PDF",
    "dashboard.taxDeductionInfo": "Informasi Pengurangan Pajak",
    "dashboard.taxInfo1": "Semua donasi ke amal terdaftar dapat dikurangkan pajak di Indonesia",
    "dashboard.taxInfo2": "Simpan bukti ini dengan dokumen pengajuan pajak tahunan Anda",
    "dashboard.taxInfo3": "Berkonsultasi dengan profesional pajak untuk saran yang dipersonalisasi",
    "dashboard.participateInPlatform": "Berpatisipasi dalam keputusan platform dengan kekuatan suara Anda",
    "dashboard.voteOnDecisions": "Suara pada keputusan platform penting",
    "dashboard.viewAll": "Lihat Semua",
    "dashboard.manageWallet": "Kelola koneksi dan preferensi dompet Anda",
    "dashboard.connectedWallet": "Dompet Terhubung",
    "dashboard.walletAddress": "Alamat",
    "dashboard.disconnect": "Putuskan",
    "dashboard.network": "Jaringan",
    "dashboard.balance": "Saldo",
    "dashboard.notificationPreferences": "Preferensi Notifikasi",
    "dashboard.chooseNotified": "Pilih bagaimana Anda ingin diberitahu",
    "dashboard.donationConfirmations": "Konfirmasi Donasi",
    "dashboard.donationConfirmationsDesc": "Dapatkan notifikasi saat donasi Anda diproses",
    "dashboard.newProposals": "Proposal Baru",
    "dashboard.newProposalsDesc": "Peringatan untuk proposal tata kelola DAO baru",
    "dashboard.campaignUpdates": "Pembaruan Kampanye",
    "dashboard.campaignUpdatesDesc": "Pembaruan dari kampanye yang telah Anda dukung",
    "dashboard.taxReportNotifications": "Laporan Pajak",
    "dashboard.taxReportNotificationsDesc": "Notifikasi ketersediaan laporan pajak tahunan",
    "dashboard.enabled": "Diaktifkan",

    // Auditor Dashboard
    "auditor.title": "Zakat Audit",
    "auditor.subtitle": "Portal Kepatuhan Syariah",
    "auditor.ecosystemOverview": "Ikhtisar Ekosistem",
    "auditor.kycVerification": "Verifikasi KYC",
    "auditor.organizationsNav": "Organisasi",
    "auditor.auditLogs": "Log Audit",
    "auditor.riskAlerts": "Peringatan Risiko",
    "auditor.verifyOrReject": "Verifikasi atau tolak pengiriman KYC proposal",
    "auditor.updateKycStatus": "Perbarui Status KYC Proposal",
    "auditor.updateKycDesc": "Verifikasi atau tolak pengiriman KYC proposal (memerlukan KYC_ORACLE_ROLE)",
    "auditor.proposalId": "ID Proposal",
    "auditor.proposalIdPlaceholder": "Masukkan ID proposal (contoh: 1)",
    "auditor.verificationNotes": "Catatan Verifikasi",
    "auditor.verificationNotesRequired": "Catatan Verifikasi *",
    "auditor.verificationNotesPlaceholder": "Masukkan catatan verifikasi atau alasan (contoh: 'Diverifikasi melalui pemeriksaan ID pemerintah dan dokumen registrasi organisasi')",
    "auditor.notesStored": "Catatan akan disimpan di blockchain dan terlihat oleh semua pengguna",
    "auditor.verifyKyc": "Verifikasi KYC",
    "auditor.rejectKyc": "Tolak KYC",
    "auditor.processing": "Memproses...",
    "auditor.kycUpdated": "Status KYC berhasil diperbarui!",
    "auditor.error": "Kesalahan:",
    "auditor.kycRoleError": "Pastikan dompet Anda memiliki KYC_ORACLE_ROLE yang diberikan oleh admin DAO",
    "auditor.yourWallet": "Dompet Anda",
    "auditor.kycCredentials": "Kredensial KYC Oracle",
    "auditor.connectedAs": "Terhubung sebagai:",
    "auditor.notConnected": "Tidak terhubung",
    "auditor.roleWarning": "Pastikan dompet ini memiliki KYC_ORACLE_ROLE yang diberikan oleh admin DAO",
    "auditor.howToVerify": "Cara Memverifikasi KYC",
    "auditor.verifyInstructions": "Masukkan ID Proposal yang ingin Anda verifikasi. Tinjau detail proposal yang muncul. Periksa dokumen KYC penyelenggara (off-chain). Tambahkan catatan verifikasi yang menjelaskan keputusan Anda. Klik \"Verifikasi KYC\" untuk menyetujui atau \"Tolak KYC\" untuk menolak. Tandatangani transaksi di dompet Anda. Tunggu konfirmasi blockchain.",
    "auditor.monitoring": "Memantau",
    "auditor.laznasNgos": "Laznas dan NGO",
    "auditor.inRealtime": "secara real-time.",
    "auditor.searchOrgHash": "Cari organisasi atau hash...",
    "auditor.exportReport": "Ekspor Laporan",
    "auditor.totalNationalZakat": "Zakat Nasional Total",
    "auditor.tracedOnBlockchain": "Ditelusuri di Blockchain",
    "auditor.activeOrganizations": "Organisasi Aktif",
    "auditor.compliant": "Patuh",
    "auditor.underReview": "Dalam Tinjauan",
    "auditor.complianceRate": "Tingkat Kepatuhan",
    "auditor.basedOnAudits": "Berdasarkan audit real-time",
    "auditor.organizationStatus": "Status Organisasi",
    "auditor.realTimeCompliance": "Pemantauan kepatuhan real-time.",
    "auditor.fundAllocation": "Alokasi Dana",
    "auditor.auditStatus": "Status Audit",
    "auditor.riskScore": "Skor Risiko",
    "auditor.details": "Detail",
    "auditor.liveAuditLog": "Log Audit Langsung",
    "auditor.immutableRecords": "Catatan blockchain yang kekal.",
    "auditor.allOrganizations": "Semua Organisasi",
    "auditor.searchOrg": "Cari organisasi...",
    "auditor.actions": "Tindakan",
    "auditor.viewDetails": "Lihat Detail",
    "auditor.allAuditEntries": "Semua Entri Audit",
    "auditor.chronologicalView": "Tampilan kronologis semua aktivitas platform",
    "auditor.completeAuditTrail": "Jejak audit blockchain lengkap yang kekal",
    "auditor.riskAlertsTitle": "Peringatan Risiko",
    "auditor.monitorAddress": "Pantau dan tangani masalah kepatuhan potensial",
    "auditor.criticalAlerts": "Peringatan Kritis",
    "auditor.immediateAction": "Tindakan segera diperlukan",
    "auditor.mediumPriority": "Prioritas Menengah",
    "auditor.reviewRecommended": "Tinjau disarankan",
    "auditor.resolved": "Diselesaikan",
    "auditor.thisMonth": "Bulan ini",
    "auditor.activeAlerts": "Peringatan Aktif",
    "auditor.investigate": "Selidiki",
    "auditor.resolve": "Selesaikan",

    // How It Works
    "howItWorks.title": "Bagaimana Cara Kerjanya",
    "howItWorks.subtitle":
      "Donasi Anda disalurkan dengan aman dan transparan",
    "howItWorks.step1.title": "Hubungkan Dompet",
    "howItWorks.step1.desc":
      "Hubungkan dompet crypto Anda untuk memulai berdonasi",
    "howItWorks.step2.title": "Pilih Kampanye",
    "howItWorks.step2.desc":
      "Pilih kampanye yang ingin Anda dukung dari daftar kampanye yang terverifikasi",
    "howItWorks.step3.title": "Berdonasi",
    "howItWorks.step3.desc":
      "Kirim donasi Anda dengan aman melalui blockchain",
    "howItWorks.step4.title": "Lacak Donasi",
    "howItWorks.step4.desc":
      "Pantau penggunaan donasi Anda secara real-time dan transparan",

    // Featured Campaigns
    "campaigns.title": "Kampanye Unggulan",
    "campaigns.subtitle": "Kampanye yang sedang membutuhkan dukungan Anda",
    "campaigns.viewAll": "Lihat Semua Kampanye",
    "campaigns.raised": "Terkumpul",
    "campaigns.of": "dari",
    "campaigns.backers": "Donatur",
    "campaigns.daysLeft": "Hari Lagi",
    "campaigns.donate": "Donasi Sekarang",
    "campaigns.learnMore": "Pelajari Lebih Lanjut",

    // Zakat Calculator
    "zakat.title": "Kalkulator Zakat",
    "zakat.subtitle":
      "Hitung zakat Anda dan salurkan langsung ke kampanye yang tepat",
    "zakat.calculator": "Kalkulator Zakat",
    "zakat.monthlyIncome": "Pendapatan Bulanan",
    "zakat.monthlyIncomePlaceholder": "Masukkan pendapatan bulanan Anda",
    "zakat.nisab": "Nisab",
    "zakat.nisabPlaceholder": "Masukkan nilai nisab (opsional)",
    "zakat.nisabHelper": "Nisab saat ini: 85 gram emas (~Rp 85,000,000)",
    "zakat.calculate": "Hitung Zakat",
    "zakat.reset": "Reset",
    "zakat.results": "Hasil Perhitungan",
    "zakat.yourIncome": "Pendapatan Anda",
    "zakat.nisabValue": "Nilai Nisab",
    "zakat.calculatedZakat": "Zakat yang Harus Dibayar",
    "zakat.walletBalance": "Saldo Dompet",
    "zakat.payZakat": "Bayar Zakat",
    "zakat.connectFirst": "Hubungkan Dompet Terlebih Dahulu",
    "zakat.insufficientBalance": "Saldo Tidak Cukup",
    "zakat.belowNisab": "Di Bawah Nisab",
    "zakat.enterIncome": "Masukkan Pendapatan",
    "zakat.notEligible":
      "Pendapatan Anda di bawah nisab. Zakat tidak wajib, tetapi sedekah tetap dianjurkan.",

    // Campaign Selection Dialog
    "campaignSelect.title": "Pilih Kampanye untuk Donasi",
    "campaignSelect.description":
      "Pilih kampanye yang ingin Anda dukung dengan zakat Anda",
    "campaignSelect.amount": "Jumlah Zakat",
    "campaignSelect.search": "Cari kampanye...",
    "campaignSelect.progress": "Progress",
    "campaignSelect.selectCampaign": "Pilih Kampanye",
    "campaignSelect.cancel": "Batal",

    // Payment Confirmation Dialog
    "confirm.title": "Konfirmasi Pembayaran Zakat",
    "confirm.description": "Periksa detail pembayaran Anda sebelum melanjutkan",
    "confirm.campaign": "Kampanye",
    "confirm.amount": "Jumlah",
    "confirm.currentBalance": "Saldo Saat Ini",
    "confirm.afterPayment": "Setelah Pembayaran",
    "confirm.blockchain": "Blockchain",
    "confirm.blockchainNote":
      "Transaksi Anda akan dicatat di blockchain untuk transparansi penuh",
    "confirm.confirmPayment": "Konfirmasi Pembayaran",
    "confirm.goBack": "Kembali",
    "confirm.processing": "Memproses...",

    // Toast Messages
    "toast.success": "Berhasil!",
    "toast.zakatPaid": "Zakat Anda telah berhasil disalurkan ke",
    "toast.txHash": "Hash Transaksi",
    "toast.error": "Terjadi kesalahan",
    "toast.paymentFailed": "Pembayaran gagal. Silakan coba lagi.",

    // Footer
    "footer.description":
      "Platform donasi transparan berbasis blockchain untuk Indonesia yang lebih baik.",
    "footer.about": "Tentang",
    "footer.aboutUs": "Tentang Kami",
    "footer.howItWorks": "Cara Kerja",
    "footer.transparency": "Transparansi",
    "footer.contact": "Kontak",
    "footer.resources": "Sumber Daya",
    "footer.documentation": "Dokumentasi",
    "footer.faq": "FAQ",
    "footer.blog": "Blog",
    "footer.community": "Komunitas",
    "footer.legal": "Hukum",
    "footer.privacy": "Kebijakan Privasi",
    "footer.terms": "Syarat & Ketentuan",
    "footer.cookies": "Kebijakan Cookie",
    "footer.rights": "Hak Cipta Dilindungi",

    // Dashboard
    "dashboard.donor": "Dasbor Donatur",
    "dashboard.organization": "Dasbor Organisasi",
    "dashboard.auditor": "Dasbor Auditor",

    // Common
    "common.currency": "IDRX",
    "common.loading": "Memuat...",
    "common.error": "Terjadi Kesalahan",
    "common.retry": "Coba Lagi",
    "common.close": "Tutup",
    "common.save": "Simpan",
    "common.edit": "Edit",
    "common.delete": "Hapus",
    "common.viewDetails": "Lihat Detail",
  },
  en: {
    // Header
    "header.search": "Search campaigns, organizations...",
    "header.campaigns": "Campaigns",
    "header.zakat": "Zakat",
    "header.faucet": "Faucet",
    "header.governance": "Governance",
    "header.dashboard": "Dashboard",
    "header.explorer": "Explorer",
    "header.contact": "Contact",
    "header.start_campaign": "Start Campaign",
    "header.connectWallet": "Connect Wallet",
    "header.disconnect": "Disconnect",
    "header.balance": "Balance",

    // Hero Section
    "hero.title": "Transparent Blockchain-Based Donation Platform",
    "hero.subtitle":
      "Donate securely and transparently through blockchain technology. Every donation is recorded and can be tracked in real-time.",
    "hero.startDonating": "Start Donating",
    "hero.exploreCampaigns": "Explore Campaigns",
    "hero.badge": "Blockchain Traced",
    "hero.statDonated": "DONATED",
    "hero.statTraceable": "TRACEABLE",
    "hero.statDonors": "DONORS",

    // Landing Roles Section
    "landing.roles.title": "Choose Your Role",
    "landing.roles.subtitle": "Select your role and start making a difference",
    "landing.roles.donor.title": "Donor",
    "landing.roles.donor.desc": "Support donations, receive NFT proof, participate in governance",
    "landing.roles.donor.button": "Start Donating",
    "landing.roles.org.title": "Organization",
    "landing.roles.org.desc": "Create Zakat campaigns, collect funds, verify by Sharia Council",
    "landing.roles.org.button": "Start Organization",
    "landing.roles.gov.title": "Governance",
    "landing.roles.gov.desc": "Participate in Community DAO and Sharia Council for proposal verification",
    "landing.roles.gov.button": "Governance",

    // Trusted Section
    "trusted.title": "Trusted by Leading Institutions",
    "trusted.subtitle": "We partner with certified organizations and use blockchain technology to ensure 100% transparency and compliance.",
    "trusted.sharia.title": "Sharia Compliant",
    "trusted.sharia.desc": "Following Islamic principles for Zakat and Waqf compliance.",
    "trusted.award.title": "Award Winning",
    "trusted.award.desc": "2nd Place Winner of Zakat Innovation Challenge by Baznas.",
    "trusted.blockchain.title": "Blockchain Secured",
    "trusted.blockchain.desc": "Every transaction is recorded on-chain for immutable proof.",

    // Campaign Card
    "campaign.by": "by",
    "campaign.verified": "Verified",
    "campaign.unverified": "Unverified",
    "campaign.donors": "donors",
    "campaign.daysLeft": "days left",
    "campaign.familiesHelped": "families helped",
    "campaign.donate": "Donate Now",

    // Campaigns Page
    "campaigns.explore": "Explore Campaigns",
    "campaigns.search": "Search campaigns...",
    "campaigns.categories": "Categories",
    "campaigns.location": "Location",
    "campaigns.organization": "Organization",
    "campaigns.noCategories": "No categories",
    "campaigns.noLocations": "No locations",
    "campaigns.noOrganizations": "No organizations",
    "campaigns.error": "Error loading campaigns",
    "campaigns.noResults": "No campaigns found",
    "campaigns.clearSearch": "Clear search",
    "campaigns.loadMore": "Load More Campaigns",
    "campaigns.retry": "Try Again",
    "campaigns.sort": "Sort",
    "campaigns.campaignCount": "campaigns",
    "campaigns.findAndSupport": "Find and support verified causes that matter to you.",

    // Footer
    "footer.poweredBy": "Powered by",
    "footer.awardBadge": "2nd Place Winner - Zakat Innovation Challenge by Baznas",
    "footer.platform": "Platform",
    "footer.forUsers": "For Users",
    "footer.forOrganizations": "For Organizations",
    "footer.legalColumn": "Legal",
    "footer.allRights": "All Rights Reserved",
    "footer.exploreCampaigns": "Explore Campaigns",
    "footer.daoGovernance": "DAO Governance",
    "footer.impactReports": "Impact Reports",
    "footer.donorDashboard": "Donor Dashboard",
    "footer.myDonations": "My Donations",
    "footer.becomePartner": "Become a Partner",
    "footer.organizationDashboard": "Organization Dashboard",
    "footer.verificationProcess": "Verification Process",
    "footer.resourcesColumn": "Resources",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.shariaCompliance": "Sharia Compliance",
    "footer.auditLogs": "Audit Logs",
    "footer.description": "The world's first fully traceable Zakat and donation platform. Empowering transparent giving through blockchain technology.",

    // Dashboard
    "dashboard.totalDonated": "Total Donated",
    "dashboard.campaignsSupported": "Campaigns Supported",
    "dashboard.governancePower": "Governance Power",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.walletBalance": "Wallet Balance",
    "dashboard.overview": "Overview",
    "dashboard.taxReports": "Tax Reports",
    "dashboard.governanceDao": "Governance (DAO)",
    "dashboard.walletSettings": "Wallet Settings",
    "dashboard.editProfile": "Edit Profile",
    "dashboard.myNftReceipts": "My NFT Receipts",
    "dashboard.donationHistory": "Donation History",
    "dashboard.daoProposals": "DAO Proposals",
    "dashboard.recentDonations": "Recent Donations",
    "dashboard.thisMonth": "This Month",
    "dashboard.totalImpact": "Total Impact",
    "dashboard.categories": "Categories",
    "dashboard.date": "Date",
    "dashboard.campaignColumn": "Campaign",
    "dashboard.amount": "Amount",
    "dashboard.type": "Type",
    "dashboard.transaction": "Transaction",
    "dashboard.yourVotingPower": "Your Voting Power",
    "dashboard.soulboundTokens": "Soul-bound tokens earned through donations",
    "dashboard.proposalsVoted": "Proposals Voted",
    "dashboard.participationRate": "Participation Rate",
    "dashboard.activeProposals": "Active Proposals",
    "dashboard.endsIn": "Ends in",
    "dashboard.voteFor": "Vote For",
    "dashboard.voteAgainst": "Vote Against",
    "dashboard.howToEarnMore": "How to Earn More Voting Power",
    "dashboard.downloadTaxReports": "Download Tax Reports",
    "dashboard.taxDeductible": "Tax Deductible",
    "dashboard.totalDeductible": "Total Deductible",
    "dashboard.taxBenefitEstimate": "Tax Benefit Estimate",
    "dashboard.taxRate": "tax rate",
    "dashboard.annualReports": "Annual Reports",
    "dashboard.taxYear": "Tax Year",
    "dashboard.inProgressYtd": "In Progress - YTD",
    "dashboard.complete": "Complete",
    "dashboard.downloadPdf": "Download PDF",
    "dashboard.taxDeductionInfo": "Tax Deduction Information",
    "dashboard.taxInfo1": "All donations to registered charities are tax-deductible in Indonesia",
    "dashboard.taxInfo2": "Keep these receipts with your annual tax filing documentation",
    "dashboard.taxInfo3": "Consult with a tax professional for personalized advice",
    "dashboard.participateInPlatform": "Participate in platform decisions with your voting power",
    "dashboard.voteOnDecisions": "Vote on important platform decisions",
    "dashboard.viewAll": "View All",
    "dashboard.manageWallet": "Manage your wallet connection and preferences",
    "dashboard.connectedWallet": "Connected Wallet",
    "dashboard.walletAddress": "Address",
    "dashboard.disconnect": "Disconnect",
    "dashboard.network": "Network",
    "dashboard.balance": "Balance",
    "dashboard.notificationPreferences": "Notification Preferences",
    "dashboard.chooseNotified": "Choose how you want to be notified",
    "dashboard.donationConfirmations": "Donation Confirmations",
    "dashboard.donationConfirmationsDesc": "Get notified when your donations are processed",
    "dashboard.newProposals": "New Proposals",
    "dashboard.newProposalsDesc": "Alerts for new DAO governance proposals",
    "dashboard.campaignUpdates": "Campaign Updates",
    "dashboard.campaignUpdatesDesc": "Updates from campaigns you have supported",
    "dashboard.taxReportNotifications": "Tax Reports",
    "dashboard.taxReportNotificationsDesc": "Annual tax report availability notifications",
    "dashboard.enabled": "Enabled",

    // Auditor Dashboard
    "auditor.title": "Zakat Audit",
    "auditor.subtitle": "Sharia Compliance Portal",
    "auditor.ecosystemOverview": "Ecosystem Overview",
    "auditor.kycVerification": "KYC Verification",
    "auditor.organizationsNav": "Organizations",
    "auditor.auditLogs": "Audit Logs",
    "auditor.riskAlerts": "Risk Alerts",
    "auditor.verifyOrReject": "Verify or reject proposal KYC submissions",
    "auditor.updateKycStatus": "Update Proposal KYC Status",
    "auditor.updateKycDesc": "Verify or reject proposal KYC submissions (requires KYC_ORACLE_ROLE)",
    "auditor.proposalId": "Proposal ID",
    "auditor.proposalIdPlaceholder": "Enter proposal ID (e.g., 1)",
    "auditor.verificationNotes": "Verification Notes",
    "auditor.verificationNotesRequired": "Verification Notes *",
    "auditor.verificationNotesPlaceholder": "Enter verification notes or reasoning (e.g., 'Verified via government ID check and organization registration documents')",
    "auditor.notesStored": "Notes will be stored on-chain and visible to all users",
    "auditor.verifyKyc": "Verify KYC",
    "auditor.rejectKyc": "Reject KYC",
    "auditor.processing": "Processing...",
    "auditor.kycUpdated": "KYC status updated successfully!",
    "auditor.error": "Error:",
    "auditor.kycRoleError": "Make sure your wallet has KYC_ORACLE_ROLE granted by the DAO admin",
    "auditor.yourWallet": "Your Wallet",
    "auditor.kycCredentials": "KYC Oracle credentials",
    "auditor.connectedAs": "Connected as:",
    "auditor.notConnected": "Not connected",
    "auditor.roleWarning": "Make sure this wallet has KYC_ORACLE_ROLE granted by the DAO admin",
    "auditor.howToVerify": "How to Verify KYC",
    "auditor.verifyInstructions": "Enter the Proposal ID you want to verify. Review the proposal details that appear. Check the organizer's KYC documents (off-chain). Add detailed verification notes explaining your decision. Click \"Verify KYC\" to approve or \"Reject KYC\" to deny. Sign the transaction in your wallet. Wait for blockchain confirmation.",
    "auditor.monitoring": "Monitoring",
    "auditor.laznasNgos": "Laznas and NGOs",
    "auditor.inRealtime": "in real-time.",
    "auditor.searchOrgHash": "Search organization or hash...",
    "auditor.exportReport": "Export Report",
    "auditor.totalNationalZakat": "Total National Zakat",
    "auditor.tracedOnBlockchain": "Traced on Blockchain",
    "auditor.activeOrganizations": "Active Organizations",
    "auditor.compliant": "Compliant",
    "auditor.underReview": "Under Review",
    "auditor.complianceRate": "Compliance Rate",
    "auditor.basedOnAudits": "Based on real-time audits",
    "auditor.organizationStatus": "Organization Status",
    "auditor.realTimeCompliance": "Real-time compliance monitoring.",
    "auditor.fundAllocation": "Fund Allocation",
    "auditor.auditStatus": "Audit Status",
    "auditor.riskScore": "Risk Score",
    "auditor.details": "Details",
    "auditor.liveAuditLog": "Live Audit Log",
    "auditor.immutableRecords": "Immutable blockchain records.",
    "auditor.allOrganizations": "All Organizations",
    "auditor.searchOrg": "Search organization...",
    "auditor.actions": "Actions",
    "auditor.viewDetails": "View Details",
    "auditor.allAuditEntries": "All Audit Entries",
    "auditor.chronologicalView": "Chronological view of all platform activities",
    "auditor.completeAuditTrail": "Complete immutable blockchain audit trail",
    "auditor.riskAlertsTitle": "Risk Alerts",
    "auditor.monitorAddress": "Monitor and address potential compliance issues",
    "auditor.criticalAlerts": "Critical Alerts",
    "auditor.immediateAction": "Immediate action required",
    "auditor.mediumPriority": "Medium Priority",
    "auditor.reviewRecommended": "Review recommended",
    "auditor.resolved": "Resolved",
    "auditor.thisMonth": "This month",
    "auditor.activeAlerts": "Active Alerts",
    "auditor.investigate": "Investigate",
    "auditor.resolve": "Resolve",

    // How It Works
    "howItWorks.title": "How It Works",
    "howItWorks.subtitle": "Your donations are delivered safely and transparently",
    "howItWorks.step1.title": "Connect Wallet",
    "howItWorks.step1.desc":
      "Connect your crypto wallet to start donating",
    "howItWorks.step2.title": "Choose Campaign",
    "howItWorks.step2.desc":
      "Select a campaign you want to support from our verified campaigns",
    "howItWorks.step3.title": "Donate",
    "howItWorks.step3.desc":
      "Send your donation securely through blockchain",
    "howItWorks.step4.title": "Track Donation",
    "howItWorks.step4.desc":
      "Monitor your donation usage in real-time and transparently",

    // Featured Campaigns
    "campaigns.title": "Featured Campaigns",
    "campaigns.subtitle": "Campaigns that need your support",
    "campaigns.viewAll": "View All Campaigns",
    "campaigns.raised": "Raised",
    "campaigns.of": "of",
    "campaigns.backers": "Backers",
    "campaigns.daysLeft": "Days Left",
    "campaigns.donate": "Donate Now",
    "campaigns.learnMore": "Learn More",

    // Zakat Calculator
    "zakat.title": "Zakat Calculator",
    "zakat.subtitle":
      "Calculate your zakat and donate directly to the right campaign",
    "zakat.calculator": "Zakat Calculator",
    "zakat.monthlyIncome": "Monthly Income",
    "zakat.monthlyIncomePlaceholder": "Enter your monthly income",
    "zakat.nisab": "Nisab",
    "zakat.nisabPlaceholder": "Enter nisab value (optional)",
    "zakat.nisabHelper": "Current nisab: 85 grams of gold (~Rp 85,000,000)",
    "zakat.calculate": "Calculate Zakat",
    "zakat.reset": "Reset",
    "zakat.results": "Calculation Results",
    "zakat.yourIncome": "Your Income",
    "zakat.nisabValue": "Nisab Value",
    "zakat.calculatedZakat": "Zakat to Pay",
    "zakat.walletBalance": "Wallet Balance",
    "zakat.payZakat": "Pay Zakat",
    "zakat.connectFirst": "Connect Wallet First",
    "zakat.insufficientBalance": "Insufficient Balance",
    "zakat.belowNisab": "Below Nisab",
    "zakat.enterIncome": "Enter Income",
    "zakat.notEligible":
      "Your income is below nisab. Zakat is not obligatory, but charity is still encouraged.",

    // Campaign Selection Dialog
    "campaignSelect.title": "Select Campaign to Donate",
    "campaignSelect.description":
      "Choose a campaign you want to support with your zakat",
    "campaignSelect.amount": "Zakat Amount",
    "campaignSelect.search": "Search campaigns...",
    "campaignSelect.progress": "Progress",
    "campaignSelect.selectCampaign": "Select Campaign",
    "campaignSelect.cancel": "Cancel",

    // Payment Confirmation Dialog
    "confirm.title": "Confirm Zakat Payment",
    "confirm.description": "Review your payment details before proceeding",
    "confirm.campaign": "Campaign",
    "confirm.amount": "Amount",
    "confirm.currentBalance": "Current Balance",
    "confirm.afterPayment": "After Payment",
    "confirm.blockchain": "Blockchain",
    "confirm.blockchainNote":
      "Your transaction will be recorded on blockchain for full transparency",
    "confirm.confirmPayment": "Confirm Payment",
    "confirm.goBack": "Go Back",
    "confirm.processing": "Processing...",

    // Toast Messages
    "toast.success": "Success!",
    "toast.zakatPaid": "Your zakat has been successfully donated to",
    "toast.txHash": "Transaction Hash",
    "toast.error": "An error occurred",
    "toast.paymentFailed": "Payment failed. Please try again.",

    // Footer
    "footer.description":
      "Transparent blockchain-based donation platform for a better Indonesia.",
    "footer.about": "About",
    "footer.aboutUs": "About Us",
    "footer.howItWorks": "How It Works",
    "footer.transparency": "Transparency",
    "footer.contact": "Contact",
    "footer.resources": "Resources",
    "footer.documentation": "Documentation",
    "footer.faq": "FAQ",
    "footer.blog": "Blog",
    "footer.community": "Community",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms & Conditions",
    "footer.cookies": "Cookie Policy",
    "footer.rights": "All Rights Reserved",

    // Dashboard
    "dashboard.donor": "Donor Dashboard",
    "dashboard.organization": "Organization Dashboard",
    "dashboard.auditor": "Auditor Dashboard",

    // Common
    "common.currency": "IDRX",
    "common.loading": "Loading...",
    "common.error": "An Error Occurred",
    "common.retry": "Try Again",
    "common.close": "Close",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.viewDetails": "View Details",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en"); // Default to English

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.id] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
