// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.31;

/**
 * @title HonkVerifier
 * @notice Interface for the UltraHONK proof verifier deployed on-chain.
 * @dev The actual verifier contract is generated by Barretenberg's
 *      `bb write_solidity_verifier` and deployed separately due to its
 *      large code size (~34 KB runtime, 2,461 lines).
 *      This interface provides the ABI needed by ZKTCore to call verify().
 */
interface IHonkVerifier {
    /**
     * @notice Verify an UltraHONK proof
     * @param proof The proof bytes (msgpack format, ~8 KB)
     * @param publicInputs Array of public inputs (field elements as bytes32)
     * @return True if the proof is valid
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external returns (bool);
}

/**
 * @title HonkVerifier
 * @notice Deployed UltraHONK verifier. The full implementation is compiled
 *         and deployed separately. This contract serves as a type-safe
 *         wrapper around the deployed verifier's address.
 */
contract HonkVerifier is IHonkVerifier {
    // Full verifier compiled separately via `bb write_solidity_verifier`
    // Deployed using its precompiled bytecode artifact.
    // This wrapper is NOT the verifier — it just defines the ABI.
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external view virtual returns (bool) {
        // Overridden in the actual deployed verifier
        return false;
    }
}
